name       : libxxf86vm
version    : 1.1.5
release    : 15
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXxf86vm-1.1.5.tar.gz : f3f1c29fef8accb0adbd854900c03c6c42f1804f2bc1e4f3ad7b2e1f3b878128
license    : MIT
component  : xorg.library
summary    : X11 XFree86 video mode extension library
description: |
    libXxf86vm provides an interface to the XFree86-VidModeExtension extension, which allows client applications to get and set video mode timings in extensive detail.  It is used by the xvidtune program in particular.
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(x11)
    - pkgconfig(xproto)
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
