name       : libxxf86vm
version    : 1.1.4
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXxf86vm-1.1.4.tar.gz : 5108553c378a25688dcb57dca383664c36e293d60b1505815f67980ba9318a99
license    : MIT
summary    : X11 XFree86 video mode extension library
component  : xorg.library
builddeps  :
    - pkgconfig(xf86vidmodeproto)
    - pkgconfig32(xext)
    - pkgconfig(xext)
    - pkgconfig32(x11)
    - pkgconfig(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
description: |
    libXxf86vm provides an interface to the XFree86-VidModeExtension extension, which allows client applications to get and set video mode timings in extensive detail.  It is used by the xvidtune program in particular.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
